### ISSUE TITLE
Conflict between ossuuid and libuuid

### ISSUE THREAD

**Issue by xylar** [conda-forge/libcf-feedstock#20]
This library brings in `ossuuid`, which conflicts with `libuuid`:

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.a'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.la'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.so'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/pkgconfig/uuid.pc'
```

Would it be possible to build against `libuuid` instead?

See https://github.com/E3SM-Project/e3sm-unified/pull/39

**Comment by xylar** [comment]
@doutriaux1 and @dnadeau4, if I put in a PR to switch from `ossuuid` to `libuuid`, would that be welcome?  I think I will go ahead and do that unless I hear otherwise.

**Comment by dnadeau4** [comment]
@xylar  two-three years ago I wanted to change `ossuuid` to `libuuid`  I remember that I could get the `uuid` with both library for the `tracking_id` metadata in `CMOR`.   I don't remember what stopped me from changing the library.   Where are you using `libuuid`?

**Comment by xylar** [comment]
`libuuid` comes in through `pyqt`, which is used by `spyder`, `jupyter` and `matplotlib` (possibly among others).  `cdat` it also trying to use both `ossuuid` (via `libcf`) and `libuuid` (via `spyder`, `jupyter` and `matplotlib`) so the problem should already be there for you guys, it maybe just went unnoticed.

**Comment by xylar** [comment]
I discovered a handy little tool for helping me figure out these dependencies this morning:
https://github.com/rvalieris/conda-tree
